### PR TITLE
Restart Feature

### PR DESCRIPTION
**Pull request by Stevo15025**
The improvements in this branch include

1. Function to read in an already successful trip. This gives us a much nicer starting point. And starting back with a higher temperature means that if we were in a local minimum we can sample out of it and keep searching the whole space again. It's sort of like restarting.

2. We now save the best trip throughout the entire annealing process, Since the process can become divergent at points we want to take the trip with the minimum loss throughout the sampling process.

3. I changed the sampling space for both the global and local searches so they are much smaller. It seems in a paper I found ([here](http://read.pudn.com/downloads91/sourcecode/math/351710/SA_TSP/Simulated_Annealing_Support_Document.pdf)) as well as the wiki on simulated annealing that sampling swaps closer to one another is better. (I wonder if we should still have a large insertion sample space though)

4. Changed names of functions to be more descriptive and separated the kernels for swaps, inserts, and the rng into separate headers.

5. Our city swaps are now drawn from a normal distribution instead of uniform.

6. Instead of Naively checking whether we have hit a boundry we treat cases where the sample city is greater than N or less than 0 as a circle so that they stay within the bounds

### CODE REVIEW

**Comment by Stevo15025** [comment]
@PB12203006

**Comment by Stevo15025** [comment]
I removed the restart feature as it was causing my GPU to slow down immensly. I think it was because of all the read writes between host and device.

I also move some things around so that each kernel algorithm sits in it's own header

**Comment by PB12203006** [comment]
why did you revise the acceptance back to the difference instead of quotient, the difference is not universal. It depends on the scale of location

**Comment by Stevo15025** [comment]
Oh! I think I was just messing around and was trying that out to see if their was a difference. I'll change that as soon as I'm done with the hw

**Pull request merged**
