### PR TITLE
Fix sampling

### PR DESCRIPTION
**Pull request by Stevo15025**

### CODE REVIEW

**Comment by Stevo15025** [comment]
Alright so I'm going to eat this food, resolve these conflicts, then merge this with master

**Comment by Stevo15025** [comment]
Is there anything else we should look over related to the sampling before we commit?

**Comment by PB12203006** [comment]
I think it's OK

**Comment by Stevo15025** [comment]
Actually idt this is right. It's not going below 858,959,808

I may revert to an older branch

**Comment by PB12203006** [comment]
really? let me try it

**Comment by Stevo15025** [comment]
Actually comment out the same thing

```
/*else if (optimized_loss >= optimized_loss_restart){
            sames++;
            if (sames > 80){
                T[0] = T[0] * 0.9;
                }
        }*/
```

It's not doing what I thought it was doing.

Also still need to find a good annealing temp and decay. Messing around with 10,000, but may need to go higher

**Comment by Stevo15025** [comment]
Also it's going up quite a lot

**Comment by PB12203006** [comment]
You can try commenting out acceptance for larger loss and see if the loss goes up. This time if we set the parameters right there won't be any increase.

**Comment by Stevo15025** [comment]
Yeah even with all probs turned off it goes up. I'm going to revert to the commit before that because it was decreasing

**Comment by Stevo15025** [comment]
See here
https://github.com/Stevo15025/tsp_gpu/tree/sample_lod

This version goes strictly down, though the acceptance probabilities are probably too low

**Comment by PB12203006** [comment]
Yeah, it used restart to prevent going up, but now that we discovered the reason for going up, I think we can fix it theoretically!

**Comment by Stevo15025** [comment]
Okay signing off. But I put in the correctly parametrized insert and swap methods into the branch above. Things seem to be working fine.

Now we should try to improve opt2

**Comment by PB12203006** [comment]
Yeah that's what I'm doing now, swap and insert work well

**Comment by PB12203006** [comment]
It seems in 2opt if I bound city_one <= N-5 and city_two<=N-2 there's no problem

**Comment by PB12203006** [comment]
I'm running a larger iteration to see if it's true

**Comment by PB12203006** [comment]
And it's embarrassing that I still can not run the latest version, the exact error is: too many resources required to launch...
Anyway reliable algorithm comes first, I'll check those trivial errors after presentation.

**Comment by PB12203006** [comment]
I'm sure that after setting city_one<=N-5 and city_two<=N-2 , 2-opt is then correct

**Comment by PB12203006** [comment]
Due to the weird error I can't run the latest version, and now I created a new branch containing my old fashioned, ugly but executable, monotonic version.... If you haven't fixed yours yet, you can try mine....

**Comment by PB12203006** [comment]
I'm going to run the sra104815 tonight!

**Comment by Stevo15025** [comment]
So it turns out that it does not make sense to calculate Euclidian distance in the kernel since we are only looking at a chunk of the trip and not the whole thing. Converting back to this, while keeping the better sampling method gives very good results

**Pull request closed without merging**
